In [7]:
from tfim_sk_infd.services import jij_service
from tfim_sk_infd.models.SKSpinGlass import SKSpinGlass
import numpy
import sys

numpy.set_printoptions(threshold=sys.maxsize)

T = 4

Jij_instance = jij_service.get_toy_Jij(T)
SG = SKSpinGlass(Jij_instance)

print(SG.JZZ.get_shape())

print(SG.JZZ.diagonal() )

100% |########################################################################|


Building JZZ...
Done.
Building Mx...
Done.
(16, 16)
[-2.  2.  2.  2.  0.  0.  0. -4. -4.  0.  0.  0.  2.  2.  2. -2.]


In [4]:
import numpy as np

# Original NumPy array
original_array = np.array([[1, 2, 3], [4, 5, 6]])

# Convert the NumPy array to a string
array_string = np.array2string(original_array)

In [5]:
print(array_string)

[[1 2 3]
 [4 5 6]]


In [9]:
import json
original_array = np.array([[1, 2, 3], [4, 5, 6]])

arr_str = json.dumps(original_array.tolist())
np.array(json.loads(arr_str))

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
N=8
(N*(N-1)) / 2

28.0

In [47]:
from tfim_sk_infd.services import jij_service, ground_state_service, qutip_service
import numpy as np

# Get an instance and find ground state
seed = 0
N = 8
Jij = jij_service.Jij_instance(N, seed)
JZZ = jij_service.JZZ_SK(Jij)
gs_list = np.where(JZZ.diagonal() == JZZ.diagonal().max())[0]

# Pull out half of the ground states and determine maximum hd
reduced_gs, max_h_d = ground_state_service.maximal_half_clique(gs_list, N)

print(reduced_gs)

gs_size = len(reduced_gs)

# Find quantum annealing final state
Hp = qutip_service.spin_glass_hamiltonian(Jij, N)
Ht = qutip_service.transverse_field_hamiltonian(N)

h = 1e-2
h_t = (-Hp*(1-h)) - (h * Ht)

eigenvalues, eigenstates = h_t.eigenstates(eigvals = 1)

# print(eigenstates[0])

annealing_gs_probs = qutip_service.quantum_anneal(Hp, Ht, N, 1000, 100)

[9, 30]


In [48]:
eigenstates[0].full().flatten()[gs_list]

array([0.49998355+0.j, 0.499984  +0.j, 0.49998385+0.j, 0.49998421+0.j])

In [34]:
np.array(annealing_gs_probs)[gs_list]

array([0.24999996, 0.24999996, 0.24999996, 0.24999996])

In [51]:
for h in (1, 0, 1e-1, 1e-2, 1e-3, 1e-4, 1e-5 ):
    h_t = (-Hp*(1-h)) - (h * Ht)

    # Calculate condition number
    cond_number = np.linalg.cond(h_t.full())
    print("Condition number:", cond_number)

print(np.linalg.cond(Hp.full()))

Condition number: 8.621715046583702e+17
Condition number: inf
Condition number: 1.8073537748923588e+16
Condition number: 1.1143847909944384e+17
Condition number: 6.501768394827755e+16
Condition number: 1.2890019807250006e+17
Condition number: 1.2631674856366051e+17
inf


In [60]:
h_test = Hp.full()[1:6,1:6]
print(h_test)
print(np.linalg.cond(h_test))

[[ 6.+0.j  0.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j -6.+0.j  0.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j -4.+0.j  0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  2.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j  0.+0.j  0.+0.j  4.+0.j]]
3.0


In [5]:
from tfim_sk_infd.services import ground_state_service
import numpy as np

N = 8
gs = [9,30]

overlap_dist = ground_state_service.overlap_distribution(gs, N)
overlap_dist = overlap_dist.tolist()
od_mean = np.mean(overlap_dist)
od_variance = np.var(overlap_dist)

hd = ground_state_service.base_N_hamming_distance(9,30,8)

In [6]:
print(overlap_dist)
print(od_mean)
print(od_variance)
print(hd)

[1.0, 0.0, 1.0]
0.6666666666666666
0.22222222222222224
4


In [14]:
import data_service
from database.models import InstancesN8
from tfim_sk_infd.services import qutip_service
from tfim_sk_infd.models.Jij import Jij
import numpy as np

N = 8
h = 1e-2

with data_service.get_session() as session:

    instance = session.query(InstancesN8).where(InstancesN8.seed == 1).all()[0]
    Jij_obj = Jij(np.array(instance.Jij_matrix))

    Ht = qutip_service.transverse_field_hamiltonian(N)
    Hp = qutip_service.spin_glass_hamiltonian(Jij_obj, N)

    h_t = -Hp - h * Ht

    eigenvalues, eigenstates = h_t.eigenstates(eigvals=1)

    gs_probs = [
        round(2 * float(pa.real**2 + pa.imag**2),5)
        for pa in eigenstates[0].full().flatten()[instance.reduced_gs]
    ]

    if abs(sum(gs_probs) - 1) > 1e-2:
        print(
            f"seed {instance.seed} diagonalization fail. gs prob array sum {sum(gs_probs)}\n{gs_probs}"
        )

In [15]:
gs_probs

[0.49997, 0.49997]

In [3]:
from tqdm import tqdm
import time

# Example loop
for i in tqdm(range(100)):
    # Simulate some work with a sleep
    time.sleep(0.1)

100%|██████████| 100/100 [00:10<00:00,  9.49it/s]


In [ ]:
"""
python3 -m scripts.add_instances           
python3 -m scripts.update_degeneracy_col
python3 -m scripts.update_reduced_gs_hd
python3 -m scripts.update_overlap_dist 
python3 -m scripts.update_post_anneal_gs_probs
python3 -m scripts.update_post_anneal_cols    
python3 -m scripts.update_post_anneal_gs_hd
"""